version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: bpswe-db
    restart: always
    environment:
      POSTGRES_DB: hosting_center
      POSTGRES_USER: student
      POSTGRES_PASSWORD: T!gfwo&*24@!gjw!5%
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/database.sql:/docker-entrypoint-initdb.d/database.sql

  web:
    build: .
    container_name: bpswe-app
    restart: always
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
      DB_HOST: postgres
      DB_PORT: "5432"
    volumes:
      - ./www:/var/www

  ftp:
    build: ./ftp
    container_name: bpswe-ftp
    restart: always
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      # Passive mode parameters (localhost for local, IP for production)
      - PUBLICHOST=localhost
    depends_on:
      - postgres
    volumes:
      - ./ftp/pureftpd-pgsql.conf:/etc/pure-ftpd/pureftpd-pgsql.conf:ro
      - ./www:/var/www

      
  apache:
    build: ./apache
    container_name: bpswe-apache
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./www:/var/www
    #   - ./certbot/conf:/etc/letsencrypt
    #   - ./certbot/www:/var/www/certbot

volumes:
  postgres_data:
