version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: bpswe-db
    restart: always
    environment:
      POSTGRES_DB: hosting_center
      POSTGRES_USER: student
      POSTGRES_PASSWORD: T!gfwo&*24@!gjw!5%
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/database.sql:/docker-entrypoint-initdb.d/database.sql
volumes:
  postgres_data: