PGSQLServer     bpswe-db
PGSQLPort       5432
PGSQLUser       student
PGSQLPassword   T!gfwo&*24@!gjw!5%
PGSQLDatabase   hosting_center

PGSQLCrypt      clear

PGSQLGetPW      SELECT password_hash FROM ftp_accounts WHERE username='\L'
PGSQLGetDir     SELECT directory FROM ftp_accounts WHERE username='\L'

PGSQLDefaultUID 33
PGSQLDefaultGID 33
