# PostgreSQL connection parameters
PGSQLServer postgres
PGSQLPort   5432
PGSQLUser   student
PGSQLPassword T!gfwo&*24@!gjw!5%
PGSQLDatabase hosting_center

# User authentication queries
# \L - username (login)
PGSQLGetPW SELECT "password_hash" FROM "ftp_accounts" WHERE "username" = '\L'
PGSQLGetDir SELECT "directory" FROM "ftp_accounts" WHERE "username" = '\L'

# Encryption method (crypt - SHA512 salted hash standard)
PGSQLCrypt crypt

# Map all virtual users to a single system user (see Dockerfile)
# UID 1000 - ftpuser
# GID 1000 - ftpgroup
PGSQLDefaultUID 1000
PGSQLDefaultGID 1000

# Limits and quotas (temporarily disabled for upload debugging)
# PGSQLGetQTAFS SELECT "quota" FROM "ftp_accounts" WHERE "username" = '\L'
