# MySQL connection parameters
MYSQLServer mysql
MYSQLPort   3306
MYSQLUser   student
MYSQLPassword T!gfwo&*24@!gjw!5%
MYSQLDatabase hosting_center

# User authentication queries
# \L - username (login)
MYSQLGetPW SELECT password_hash FROM ftp_accounts WHERE username='\L'
MYSQLGetDir SELECT directory FROM ftp_accounts WHERE username='\L'

# Encryption method (crypt - SHA512 salted hash standard)
MYSQLCrypt crypt

# Map all virtual users to a single system user (see Dockerfile)
# UID 1000 - ftpuser
# GID 1000 - ftpgroup
MYSQLDefaultUID 1000
MYSQLDefaultGID 1000

# Limits and quotas
# In this Pure-FTPd build (based on binary strings):
# MYSQLGetQTASZ is the Quota Size (in Megabytes)
MYSQLGetQTASZ SELECT quota FROM ftp_accounts WHERE username='\L'
# MYSQLGetQTAFS is the Quota File Count (Number of files)
MYSQLGetQTAFS SELECT 10000 FROM ftp_accounts WHERE username='\L'
