server {
    listen 80 default_server;
    listen [::]:80 default_server;
    
    # The Document Root
    root /var/www/html;
    index index.html index.php;

    server_name _;

    location / {
        try_files $uri $uri/ =404;
    }
}
